sudo: false
os:
- linux
- osx
language: node_js
node_js:
- node
- '10'
- '9'
- '8'
before_deploy:
- npm install -g rollup
- npm install --only=dev
deploy:
  provider: npm
  email: shirbr510@gmail.com
  api_key:
    secure: EafZtN+sNZbw60UqH9l8tGp1KS/ZHccdesEqUMk3/817msa9mfpzjspqWhajpabT9kMhDWspdpRNvukTdMXacFDUPIxcJ8p4CyVwApnt/5e4a1/BgVPL7MflcRFbj1TaQT9T5m8g5/nL7VTSw1KDUsG1RkNVoaU/g7UG3IFkzapYhSxY2dfbsdZtJwBCyMcs3D+U7wdgOBU81ce1WA42gi0sCJRnJBZJLoG6e9SF8mh4SdNgQtbWVuXYrvlZC3v53CbYD8f4KUnuLU7B2Ej4WY5YkiHihvA6GkmVjzHoZcY6LFSo04FXa6MRn0HK+Tb8no2sEjSGGcjTERZWTSZZOmx+r8jnQPkGxZ2KXzH8JVsxCjeyT9pSqVSYce6ZqCo0xx9Eiv/RFVJ9uABxJGf1zXD3TnQIfPG09RJW4K+Ywne/Sq1bnCrbRwifpEvVG6SlAXJEUG/81B0Y0mQPjVP/MzHlu/hH4stmaaSjHMFJb5+9dQyPxlyBKMgv9TSsi+xm1m0RICUpJSseHtET5js88uOqf9VOCoKo5gOGza4uVnmRv80RKcWCdSqAaqzFyGhOtEia/O/zlgS9wlySyNw/QFAKgIHT68xOVi3bjCZHyl3WrQeQzq2giXnMlMcb5y+MyUvGJoP/yyAuxJFO1jYtaERF/e/ffM+XFpLpWGdQQUY=
  on:
    tags: true
    repo: shirbr510/expiry-storage
